baseURL: /intradocs
title: Intradocs
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false  # Useful when translating.
enableMissingTranslationPlaceholders: false
enableRobotsTXT: true  # Search Engine Optimization
enableGitInfo: true
taxonomies:
  tag: tags
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
outputs:
  section:
    - HTML
    - RSS
    - print
# Image processing configuration.
imaging:
  resampleFilter: CatmullRom
  quality: 85
  anchor: Smart
# services:
#   googleAnalytics:
#     id: "UA-00000000-0"
# Menu links
menu: {}
  # main:
  #   name: Our Community
  #   weight: 50
  #   url: http://example.com
  #   pre: <i class="fas fa-building"></i>
# Language configuration
languages:
  en:
    contentDir: content/en
    languageName: English
    time_format_blog: 02/01/2006
    time_format_default: '2006-01-02'
    weight: 1
    params:
      time_format_blog: 02/01/2006
      time_format_default: '2006-01-02'
