# Markdown
goldmark:
  footnote: true
  parser:
    attribute:
      block: true
      title: true
  renderer:
    unsafe: true
highlight:
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style: tango
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  guessSyntax: 'true'
  tabWidth: 2
